name: Check requirements process

on:
  push:
    paths:
      - 'requirements.txt'
      - 'dependencies.txt'

jobs:
  check_requirements:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies from dependencies.txt
        run: |
          python -m pip install --upgrade pip
          pip install -r dependencies.txt

      - name: Generate requirements_check.txt
        run: pip freeze > requirements_check.txt

      - name: Compare requirements.txt with generated requirements_check.txt
        run: |
          if ! diff -u requirements.txt requirements_check.txt; then
            echo 'ERROR: requirements.txt is not up to date with dependencies.txt.'
            echo 'Please follow the process to update requirements.txt from dependencies.txt.'
            exit 1
          fi
